spring:
  application:
    name: paymentsService

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always

info:
  app:
    name: My payment service
    version: 1.0.0