version: "3.9"

services:
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  store:
    build:
      context: .
      dockerfile: store/Dockerfile
    container_name: store
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    container_name: payments
    ports:
        - "8081:8081"