version: "3.9"

services:
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - store-network

  store:
    build:
      context: .
      dockerfile: store/Dockerfile
    container_name: store
    ports:
      - "8075:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      OAUTH2_ISSUER_URI: http://keycloak:8080/realms/store-realm
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      PAYMENT_SERVICE_URL: http://payments:8081
    networks:
      - store-network

  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    container_name: payments
    ports:
        - "8081:8081"
    depends_on:
      - keycloak
    networks:
      - store-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command:
      - start-dev
      - --import-realm
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - store-network

networks:
  store-network: